const SOURCE={
w13original:['Original W13 construction — manufacturer brochure','https://www.boenicke-audio.ch/BoenickeAudio_Brochure_web.pdf'],
w13review:['Original W13 SE+ — image hifi 2021, manufacturer-hosted','https://boenicke-audio.ch/image_hifi_W13.pdf'],
mc:['Ortofon — moving-coil operation','https://ortofon.com/pages/what-is-mc'],
groove:['Ortofon — stereo groove geometry','https://ortofon.com/pages/2m-mono-se'],
w13:['Boenicke W13 — manufacturer construction & photographs','https://boenicke-audio.ch/products/loudspeakers/w13/'],
w13manual:['W13 bass amplifier — input and presets','https://boenicke-audio.ch/W13BassAmplifer.pdf'],
swingbase:['Boenicke SwingBase — steel-rope suspension principle','https://www.boenicke-audio.ch/SWING_BASE.pdf'],
pre:['Nagra HD PREAMP — original model','https://www.nagraaudio.com/product/hd-preamp/'],
premanual:['HD PREAMP owner manual — input/output selection & supply','https://www.nagraaudio.com/wp-content/uploads/2020/04/Nagra-HD-PREAMP-User-Manual-English.pdf'],
dac:['Nagra HD DAC X — documented conversion architecture','https://www.nagraaudio.com/product/hd-dac-x/'],
dacmanual:['HD DAC X owner manual — interfaces & output reference','https://www.nagraaudio.com/wp-content/uploads/2020/04/Nagra-HD-DAC-X-User-Manual-English.pdf'],
dimensions:['Nagra HD mechanical drawing — 2021','https://www.nagraaudio.com/wp-content/uploads/2021/05/HD-series-dimensions.pdf'],
amp:['Nagra Reference AMP — specifications & photography','https://www.nagraaudio.com/product/nagra-reference-amp/'],
drift:['OpenStax — model of conduction in metals','https://openstax.org/books/university-physics-volume-2/pages/9-2-model-of-conduction-in-metals'],
tem:['Texas Instruments — transmission-line propagation','https://www.ti.com/lit/pdf/SCAA082A'],
filter:['TDK — power-line EMC filter principles','https://product.tdk.com/system/files/dam/doc/product/emc/emc/power-line/general_tech_info/generaltec_power-line_en.pdf'],
sample:['Analog Devices MT-002 — sampling and aliasing','https://www.analog.com/media/en/training-seminars/tutorials/mt-002.pdf'],
quant:['Analog Devices MT-001 — quantization assumptions','https://www.analog.com/media/en/training-seminars/tutorials/mt-001.pdf'],
hold:['Analog Devices MT-017 — reconstruction and DAC images','https://www.analog.com/media/en/training-seminars/tutorials/MT-017.pdf'],
lr:['Siegfried Linkwitz — active filters','https://www.linkwitzlab.com/filters.htm'],
sound:['OpenStax — sound intensity and pressure','https://openstax.org/books/university-physics-volume-1/pages/17-3-sound-intensity'],
wave:['OpenStax — sound waves and particle displacement','https://openstax.org/books/university-physics-volume-1/pages/17-1-sound-waves'],
riaa:['Analog Devices — precision RIAA equalization','https://www.analog.com/media/en/training-seminars/design-handbooks/Op-Amp-Applications/Section6.pdf']
};
function cites(...keys){return '<p class="note">'+keys.map(k=>`<a href="${SOURCE[k][1]}" target="_blank" rel="noopener">${SOURCE[k][0]}</a>`).join('<br>')+'</p>';}
const DATA={
power:{name:'Power conditioner',short:'Power',kind:'Educational component · Parallel supply',title:'The energy behind<br>the music.',lead:'A small audio signal controls energy drawn from the mains. Power arrives through complete circuits, separately from the music.',tags:['L / N / PE','Generic filter'],object:`<h3>Conditioning, with limits</h3><p>This unbranded enclosure represents appropriately rated power distribution with interference filtering and surge protection. It is an educational design, not an internal reconstruction of your conditioner.</p><p>Filters can attenuate particular electrical interference. They do not regenerate every mains waveform, create energy or guarantee an audible improvement. Results depend on the interference and the connected impedances.</p><h3>From AC to internal rails</h3><p>Power supplies convert AC into the voltages each circuit needs. Nagra's DAC and preamp each have their own matched external PSU; the monoblocks and each W13’s integrated active subwoofer system have independent AC connections.</p><p class="note">Distribution capacity is unspecified. The conductor experiment is not total system demand. Two Reference AMPs alone each list 1,200 W maximum consumption.</p>${cites('filter','amp','premanual')}`,connections:`<h3>Three different conductors</h3><p><b>L and N</b> complete the normal load-current circuit through the source winding. Direction reverses each half-cycle. Loads connect in parallel.</p><p><b>PE</b> bonds conductive enclosures to the protective system. It is not the normal load return, although leakage can exist. A fault current must return to the source through the protective path; earth is not an energy sink.</p><div class="formula">Source L → filter → each PSU → N → source
PE → chassis safety bonds (continuous)
No extra N–PE bond in the conditioner</div><p>Each HD audio chassis receives power through two matched supply umbilicals from its own PSU. Their exact pins are not reproduced. XLR pin 1, signal return and protective earth have different jobs.</p>${cites('premanual','dacmanual')}`},
streamer:{name:'Network streamer',short:'Streamer',kind:'Educational component · Digital source',title:'Music as a sequence<br>of numbers.',lead:'A file supplies sample values. A transport delivers those values to the DAC; packet delivery is not the rhythm of the analog waveform.',tags:['USB audio','PCM laboratory'],object:`<h3>A transport, not an amplifier</h3><p>This generic streamer reads and decodes digital recordings. Its USB audio link carries data to the HD DAC X. Buffering separates bursty transport activity from the clocked conversion process.</p><p>The display is illustrative. No stream is loaded, and the exhibit sends no sound to your hardware. The sine wave lets you see timing and precision without the complexity of a recording.</p><h3>One of two entrances</h3><p>Selecting Vinyl chooses the cartridge and phono stage instead. The turntable does not feed the streamer or DAC in this installation.</p>${cites('dacmanual','sample')}`,connections:`<div class="formula">File → decode → buffer → USB data
USB → HD DAC X → stereo RCA → preamp</div><p>USB uses differential signaling with associated ground and shield conductors. A cable in the room stands for that complete cable assembly. It is not a single wire or a trail of music-bearing electrons.</p><p>Information-path highlighting has no literal electron speed or latency meaning.</p>${cites('dacmanual')}`},
dac:{name:'Nagra HD DAC X',short:'DAC',kind:'Nagra · HD line',title:'From numbers<br>to voltage.',lead:'The HD DAC X turns encoded audio into a continuously varying analog voltage. Its actual conversion architecture is distinct from the PCM teaching experiment.',tags:['FPGA → DSD256','Transformer / tube output'],object:`<h3>The documented architecture</h3><p>Nagra describes FPGA conversion to DSD256, followed by current buffering, interstage transformers and one JAN5963 output tube per channel. The matched external PSU uses supercapacitors and multiple regulated supplies.</p><div class="formula">Digital input → FPGA / DSD256
→ D/A → current buffer → transformers
→ tube output → analog RCA L/R</div><p>This is a functional block account. The proprietary modulator, conversion cells and reconstruction filter are not exposed by this exhibit.</p><h3>A recognizable object</h3><p>Photographs guide the amber modulometer, format/rate windows, input selector, suspension columns and separate PSU. The outer HD chassis envelope is approximately 438 × 439 × 121 mm at minimum foot height.</p><p class="note">Front meter movements are illustrative, not calibrated. The selector chooses input, not volume. This is the original HD DAC X, not Reference DAC. Exterior modeling approximates photography; no factory CAD was available.</p>${cites('dac','dacmanual','dimensions')}`,connections:`<div class="formula">Streamer USB → HD DAC X
RCA L/R → HD PREAMP RCA1
Matched HD PSU → two supply umbilicals</div><p>Each RCA channel has a signal center conductor and an outer signal return. The product manual gives 1.5 V RMS output at 0 dBFS. Optional balancing transformers are not assumed, so the exhibit uses RCA rather than claiming a standard balanced XLR output.</p><p>The Nagra is not modeled as a conventional PCM stair-hold circuit. Open Physics for a separate ideal sampling experiment.</p>${cites('dacmanual')}`},
turntable:{name:'Turntable',short:'Turntable',kind:'Educational component · Mechanical source',title:'A groove becomes<br>a voltage.',lead:'A diamond follows microscopic groove motion. In this moving-coil example, motion changes magnetic flux and induces a small electrical signal.',tags:['Moving coil','33⅓ / 45 RPM'],object:`<h3>A mechanical record</h3><p>The platter carries a spiral groove past the stylus. Its modulations move the cantilever and generator. Each channel's tiny coil has two terminals, completing a circuit through the phono input.</p><p>Stereo records encode channels on the two 45° groove walls. With a consistent sign convention, lateral motion represents the sum L + R and vertical motion the difference L − R. They are not independent left and right tracks.</p><h3>The model in the room</h3><p>A generic belt-drive turntable, walnut plinth, machined platter and pivoted tonearm share the system's material language. These are educational components, not undocumented Nagra products.</p><p class="note">Platter rotation follows the selected RPM. Groove/cantilever drawings are schematics at stated magnification.</p>${cites('mc','groove')}`,connections:`<div class="formula">Stylus → cantilever → L & R coils
Four cartridge leads → phono L/R inputs
Separate tonearm/chassis bond → phono chassis</div><p>The cartridge produces a signal without drawing its energy from the turntable motor supply. The motor maintains rotation; the groove and generator exchange mechanical energy.</p><p>RCA returns close the two signal circuits. A tonearm ground wire is not a substitute for these returns or for mains protective earth.</p>`},
phono:{name:'Phono stage',short:'Phono',kind:'Educational component · Low-noise gain & EQ',title:'A millivolt,<br>made useful.',lead:'A phono stage supplies gain and the playback equalization complementary to record cutting. It precedes the line-level preamp.',tags:['MC gain: 60 dB','RIAA playback'],object:`<h3>Gain and equalization</h3><p>A 0.5 mV RMS cartridge signal at 1 kHz becomes 0.5 V RMS with a voltage gain of 1,000 (60 dB), before the preamp's volume setting.</p><p>RIAA playback equalization boosts low frequencies and reduces high frequencies relative to 1 kHz. It complements the cutting response. It is not a tone preference applied to digital playback.</p><p>The three standard time constants are 3,180, 318 and 75 μs. The Physics view shows the ideal playback curve. Real phono stages also have finite headroom, input loading, noise and sometimes additional low-frequency filtering.</p>${cites('riaa')}`,connections:`<div class="formula">MC cartridge L/R → phono input loads
→ low-noise gain / RIAA → RCA2 at preamp
Supply → gain circuit → supply return</div><p>The preamp selects RCA1 (DAC) or RCA2 (phono). These alternatives meet at the selector; their signals are not combined.</p><p>For this educational phono stage, 60 dB denotes the nominal voltage gain at 1 kHz. The RIAA curve changes that gain with frequency.</p>`},
preamp:{name:'Nagra HD PREAMP',short:'Preamp',kind:'Nagra · Original HD PREAMP',title:'Choose the source.<br>Set its scale.',lead:'The preamp selects one analog source and sets the voltage delivered to the downstream branches. Its volume mechanism uses transformer taps.',tags:['Dual mono','E88CC tubes','Transformer volume'],object:`<h3>What Nagra documents</h3><p>The HD PREAMP uses a dual-mono tube signal path, two E88CC tubes and output-transformer taps for volume control, with a separate supercapacitor supply. A resistor potentiometer would misrepresent this product.</p><p>Its front panel has two volume controls, an input selector and a dual-needle modulometer. The sculpted support columns surround a narrower central enclosure.</p><h3>One output choice</h3><p>The front output selector chooses main XLR or main RCA. Here main XLR feeds a generic balanced distribution stage, allowing independent full-range feeds to the monoblocks and the W13s’ integrated active subwoofer inputs.</p><p class="note">Front meter movements are illustrative, not calibrated. The actual hardware also has separate REC/AUX outputs. They are unused here. The generic distribution stage is an educational addition.</p>${cites('pre','premanual','dimensions')}`,connections:`<div class="formula">RCA1 ← DAC (alternative source)
RCA2 ← phono (alternative source)
Selected input → level → main XLR L/R
→ high-impedance balanced distribution</div><p>The two XLR signal conductors carry the differential signal. Pin 1 connects the cable shield; chassis and protective earth remain distinct from the differential circuit.</p><p>Nagra's XLR-output ground-lift control changes the pin-1/chassis bond. It does not disconnect mains protective earth. The exhibit does not operate that switch.</p>${cites('premanual')}`},
crossover:{name:'Active crossover & distribution',short:'Crossover',kind:'Educational component · Full-range distribution + separate LR4 lab',title:'Two feeds.<br>Two amplifier systems.',lead:'The powered stage supplies two independently buffered full-range stereo feeds: one to the monoblocks and one to the W13s’ integrated active subwoofers.',tags:['Two full-range stereo feeds','LR4: separate laboratory'],object:`<h3>The installation topology</h3><p>This generic stage has a high-impedance balanced input and independent buffered outputs. One full-range stereo pair feeds the Nagra monoblocks. The other feeds the W13s’ balanced bass inputs. The active subwoofers are the opposed side drivers inside each W13.</p><p>No external low-pass or high-pass output is connected in this installation. Each W13 retains its passive mid/treble network and its own DSP low-pass and amplifiers for the integrated subwoofers.</p><h3>A separate crossover laboratory</h3><p>The Physics tab demonstrates an ideal Linkwitz–Riley fourth-order two-way system. Its low-pass and high-pass curves belong to a separate electrical experiment. Frequency, delay and polarity controls change that experiment, not the installed W13 processing.</p>${cites('lr','w13manual')}`,connections:`<div class="formula">PREAMP main XLR L/R → balanced input buffer
├ independent full-range L/R → monoblocks
└ independent full-range L/R → W13 bass XLR

No external LP or HP output is connected</div><p>Each destination has its own driven output. Left and right remain independent throughout, and amplifier output terminals are never combined.</p><p>The LR4 laboratory adds complex low-level voltages mathematically. It neither joins amplifier outputs nor represents the W13’s actual acoustic crossover response.</p>${cites('lr','w13manual')}`},
amps:{name:'Nagra Reference AMP',short:'Monoblocks',kind:'Nagra · Reference line · One channel per chassis',title:'A small voltage<br>controls real power.',lead:'Each monoblock draws on its power supply to drive one passive speaker channel. The input signal controls the output; it does not supply the speaker energy.',tags:['300 W / 8 Ω','30 W Class A · published'],object:`<h3>The exact amplifier</h3><p>These are Reference AMPs, not HD AMPs. Nagra specifies 300 W into 8 Ω, a 30 W Class A operating region and a 2,000 VA transformer. The outer envelope is 238 × 644 × 542 mm including supports.</p><p>The photographic study preserves the narrow silver tower, amber meter, selector, Reference medallion and layered outrigger feet. Smooth panels distinguish this exterior from a generic finned amplifier.</p><h3>Inside the explanation</h3><p>The Physics view uses a generic controlled voltage source and an 8 Ω resistor to explain voltage, current and power. It is not the Nagra schematic or a model of the W13's frequency-dependent impedance.</p><p class="note">Front meter movements are illustrative, not calibrated. Nagra's A/B binding posts offer different damping characteristics. They are alternative outputs, not separate frequency bands.</p>${cites('amp')}`,connections:`<div class="formula">Buffered XLR L → mono L → W13 L + / −
Buffered XLR R → mono R → W13 R + / −
Independent AC L/N/PE → each amplifier</div><p>Both speaker conductors close the output circuit through the passive speaker network. The negative post is not assumed to be protective earth. Left and right outputs are never joined.</p><p>The W13's side woofers receive power from their internal amplifiers, with a separate line input and AC feed. They do not draw their operating power from the Nagra speaker posts.</p>${cites('amp','w13manual')}`},
speakers:{name:'Boenicke W13 SE+',short:'Speakers',kind:'Boenicke · Your W13 SE+ · Photo-informed study',title:'Wood, motion<br>and a little air.',lead:'A slender wooden cabinet houses a passive mid/treble system and integrated active subwoofers. Its drivers convert local electrical forces into mechanical motion.',tags:['Twin integrated 13″ subs','6″ woodcone / 3″ wideband','Rear tweeter'],object:`<h3>The speaker in your photographs</h3><p>The published envelope is <b>105 × 18 × 39 cm</b> (height × width × depth). This slender, deep cabinet uses pale wood grain matched to your photographs; the species and finish name are not asserted.</p><p>The upper 3-inch widebander sits within a recessed wood ring. Its broad black mounting plate joins the lower plate in a clipped figure-eight, above the reddish wood midcone and stationary ash phase plug. Two glossy black 13-inch woofers face opposite sides and form the integrated active subwoofer section. The small ambient tweeter faces the rear.</p><h3>A suspended rear support</h3><p>A silver tongue enters the cabinet's low rear slot and joins a transverse crossbeam between two silver towers. The towers stand on floor discs; a small front contact provides the other support. This is not a solid plinth under the cabinet.</p><p>Boenicke documents flexible steel-rope suspension. The ropes and their terminations are concealed inside the towers and are not reconstructed. The visible support follows your photographs; its hidden mechanism has not been verified. No isolation performance or sonic improvement is inferred.</p><h3>Two amplification paths</h3><p>The external monoblock drives the passive section. The integrated side subwoofers use internal Class D amplification, rated 350 W per driver, with DSP and a separate balanced line input. The two subwoofers and their amplifiers belong to each W13 cabinet.</p><p>The front 6-inch woodcone has a first-order low-pass and no high-pass; the 3-inch widebander uses a first-order high-pass. These are electrical filter descriptions, not a measured acoustic response.</p><p class="note">Your photographs govern the visible finish, rear panel and silver SwingBase. Original-generation brochure evidence supplies construction and dimensions. Fine geometry is photograph-informed; hidden cabinet cavities and SE+ treatments are not reconstructed. Current MK2 details are not substituted.</p>${cites('w13original','w13manual','swingbase')}`,connections:`<div class="formula">Monoblock +/− → W13 passive network
Full-range line XLR → internal bass DSP
→ internal Class D channels → integrated side subs
AC L/N/PE → internal bass supply</div><p>Original bass presets are 50, 62, 78 and 98 Hz, with 12 dB/octave low-pass filters. Preset 1 (50 Hz) is retained in this conceptual installation. These electrical settings are not the complete acoustic crossover response.</p><p>The installed subwoofer crossover is the DSP inside each W13. The generic external LR4 laboratory is not connected to its drivers. The moving-coil cutaway is a generic transducer principle; the solid cabinet is not presented as a factory interior.</p>${cites('w13manual')}`},

};
const ORDER=['power','streamer','dac','turntable','phono','preamp','crossover','amps','speakers'];
const PHYSICS={
power:`<h3>Local charge motion</h3><p>This model assumes uniform current density in copper and sinusoidal 60 Hz current. Real rectifier input current can be pulsed. Fixed-center clouds represent average electron drift. They oscillate locally; they do not travel from outlet to amplifier. The normal current closes through the load and the return conductor.</p><div class="control"><label for="current">Conductor current <output id="currentOut"></output></label><input id="current" type="range" min="1" max="10" value="2" step=".1"></div><canvas class="chart" id="physicsChart" aria-label="Closed AC circuit showing local electron oscillation"></canvas><p class="note">60 Hz shown at 0.5 Hz: 120× slow motion. Displacement scale: 8 pixels/μm, enlarged. Clouds represent coherent mean drift; random microscopic motion is omitted.</p><div id="metrics"></div><div class="formula">x̂ = √2 I / (n e A · 2πf)
vₑ(t) = −i(t)/(n e A)
n = 8.5×10²⁸ m⁻³ · A = 2.08 mm²
e = 1.602176634×10⁻¹⁹ C · f = 60 Hz</div><h3>Fast field, slow drift</h3><div class="control"><label for="fieldTime">Transmission-line clock <output id="fieldTimeOut"></output></label><input id="fieldTime" type="range" min="0" max="15" step=".1" value="5"></div><canvas class="chart" id="fieldChart" aria-label="Electromagnetic step propagation along a two-metre matched transmission line"></canvas><p class="note">Separate nanosecond experiment. The shaded band is a field disturbance between paired conductors, not a travelling electron. Matched source/load; reflections omitted. Drag the clock to see arrival at the load.</p><p>A separate ideal 2 m matched, low-loss TEM line with ε<sub>eff</sub> = 2.25 has v = c/√ε<sub>eff</sub> = 1.999×10⁸ m/s, giving 10.007 ns transit. This is not a measured mains-cord speed. The AC drawing assumes negligible phase variation around a short loop.</p><h3>What the filter does</h3><p>EMI filtering suppresses specified interference under specified loading. Protective earth remains continuous. No sonic improvement or voltage regeneration is inferred.</p>${cites('drift','tem','filter')}`,
digital:`<h3>A separate PCM laboratory</h3><p>The dots are discrete samples. The green curve is one baseband sine consistent with <em>unquantized</em> samples. Sampling below the required rate makes different input tones indistinguishable.</p><div class="control"><label for="sampleRate">Samples per second, per channel</label><select id="sampleRate"><option value="8000">8,000 · educational</option><option value="16000">16,000 · educational</option><option value="32000">32,000</option><option value="44100">44,100</option><option value="48000">48,000</option><option value="96000">96,000</option></select></div><div class="control"><label for="bits">Precision</label><select id="bits"><option value="4">4 bit · educational</option><option value="8">8 bit · educational</option><option value="16">16 bit</option><option value="24">24 bit</option></select></div><canvas class="chart" id="physicsChart" aria-label="Input tone, unquantized samples, and baseband reconstruction"></canvas><div class="legend"><span><i style="background:#aaa28d"></i>Input tone</span><span><i style="background:#376657"></i>Baseband sine</span><span>● Exact samples</span></div><p class="note">Static time axis. Tone uses the global frequency control, peak 0.8 full scale, phase 0.23 rad. Anti-alias filtering is deliberately omitted to expose aliasing. This is not the DAC X circuit.</p><div id="metrics"></div><canvas class="chart" id="quantChart" aria-label="Quantization error at discrete sample instants"></canvas><p class="note">Second plot: q[n] − x[n], in LSB units. Uniform signed N-bit rounding; Δ = 2/2ᴺ, endpoints −1 to 1 − Δ. No dither; 0.8 peak avoids overload for N ≥ 4. The statistical SQNR estimate assumes uniform uncorrelated error; it is not measured SNR of this coherent undithered tone. Quantized samples are not being reconstructed by the upper sine.</p><div class="formula">x[n] = 0.8 sin(2πfn/fₛ + 0.23)
q[n] = Δ · clamp(round(x[n]/Δ))
Ideal analog: y(t) = Σ q[n] sinc(fₛt − n)</div><p>The ideal reconstruction formula assumes bandlimited interpolation of the sequence. A practical DAC has a real conversion and filtering system. Some designs hold levels internally; that unfiltered hold is not the final analog waveform. At exactly half the sample rate, samples do not uniquely determine the original sine phase and amplitude. Higher playback rate cannot repair aliasing already recorded.</p>${cites('sample','quant','hold','dac')}`,
vinyl:`<h3>Speed, wavelength and the stylus</h3><div class="control"><label for="rpm">Platter speed</label><select id="rpm"><option value="33.333333">33⅓ RPM</option><option value="45">45 RPM</option></select></div><div class="control"><label for="grooveFrequency">Recorded tone <output id="grooveOut"></output></label><input id="grooveFrequency" type="range" min="2" max="3.7" step=".01" value="3"></div><canvas class="chart" id="physicsChart" aria-label="Schematic sinusoidal groove, stylus position and induced signal"></canvas><p class="note">Lateral mono groove schematic, not a stereo groove cross-section. Motion shown at 0.5 cycle/s; displacement normalized and enlarged. Record radius 100 mm. The groove is cut at 33⅓ RPM. Its physical wavelength stays fixed when playback speed changes; pitch and duration change.</p><div id="metrics"></div><div class="formula">v = 2πr · RPM / 60
λgroove = vcut / frecorded
fplay = frecorded × RPMplay / RPMcut
emf = −N dΦ/dt</div><p>A moving-coil cartridge responds approximately to stylus velocity within its operating band. With fixed displacement amplitude, doubling frequency doubles velocity; real groove levels and pickup transfer functions complicate that simple example.</p><p>Two generator axes at 45° encode L and R. This animation isolates lateral mono motion. It does not represent the exact geometry of a particular cartridge.</p>`,
phono:`<h3>Undo the cutting curve</h3><canvas class="chart" id="physicsChart" aria-label="RIAA playback gain relative to 1 kilohertz"></canvas><div id="metrics"></div><p class="note">Static ideal RIAA playback response; normalized at 1 kHz. The marker follows the global Tone control. Additional rumble filters and actual noise/headroom are not modeled.</p><div class="formula">H(s) ∝ (1 + s·318 μs)
 / [(1 + s·3180 μs)(1 + s·75 μs)]
s = j2πf · normalize |H(1 kHz)| = 1
0.5 mV × 10^(60/20) = 0.5 V RMS</div><p>The curve is an electrical amplitude response, not the spectrum of a typical record. A recorded signal already carries the complementary cutting EQ, so this graph is not a claim that playback overemphasizes bass.</p>${cites('riaa')}`,
preamp:`<h3>Voltage, scaled</h3><p>The global Level slider sets a normalized voltage ratio. It is not a calibrated readout of the physical Nagra tap position or a prediction of SPL.</p><canvas class="chart" id="physicsChart" aria-label="Input and attenuated line voltage over time"></canvas><div id="metrics"></div><div class="formula">Vout = 1 V RMS × 10^(level/20)
Iload = Vout / 100 kΩ
Pload = Vout² / 100 kΩ</div><p class="note">Separate normalized lesson: 1 V RMS source, ideal 100 kΩ resistive input. The real DAC's full-scale output is 1.5 V RMS. Signal power delivered to this input is not preamp power consumption. Static one-cycle time axis.</p><h3>Transformer tap principle</h3><p>A changing primary current changes magnetic flux. That induces a voltage in a separate, closed secondary circuit. Selecting a tap changes the effective turns ratio and voltage. Actual winding geometry, turns and parasitics are unspecified.</p><div class="formula">Primary: drive → winding → drive return
Magnetic coupling across insulation
Secondary tap → load → winding return</div>${cites('pre','premanual')}`,
crossover:`<div class="warn">Separate laboratory: ideal matched two-way LR4 filters. Both installed W13 feeds stay full-range. This experiment’s LP and HP outputs are not connected to the installation.</div><div class="control"><label for="crossoverFrequency">Crossover <output id="crossoverOut"></output></label><input id="crossoverFrequency" type="range" min="30" max="200" value="60" step="1"></div><div class="control"><label for="delay">Extra low-band delay <output id="delayOut"></output></label><input id="delay" type="range" min="0" max="10" value="0" step=".125"></div><button class="action" id="polarity" aria-pressed="false">Invert low band</button><canvas class="chart" id="physicsChart" aria-label="LR4 low-pass, high-pass and complex sum frequency response"></canvas><div class="legend"><span><i style="background:#aa743c"></i>LP</span><span><i style="background:#557a8b"></i>HP</span><span><i style="background:#376657"></i>Complex sum</span></div><div id="metrics"></div><div class="formula">r = f/fc · D = (1 − r² + j√2r)²
LP = 1/D · HP = r⁴/D
Sum = HP + polarity · LP · e^(−j2πfτ)</div><p>At the crossover each branch is −6.02 dB, with matching phase. Their ideal undelayed sum has unity magnitude but frequency-dependent phase. Extra delay or opposite polarity changes vector addition; adding magnitudes would conceal cancellation.</p><p class="note">Graph: electrical transfer functions; log frequency, dB voltage. Ideal flat coincident drivers only. No measured speaker responses, baffle diffraction or room reflections are included. Never connect amplifier outputs together.</p>${cites('lr')}`,
amps:`<h3>A complete output circuit</h3><p>The voltage source below stands for amplifier action. Both conductors complete the load circuit. The waveform uses the global Level and Tone controls.</p><canvas class="chart" id="physicsChart" aria-label="Amplifier voltage and current in phase for an eight ohm resistor"></canvas><div id="metrics"></div><div class="formula">Vref = √(300 W × 8 Ω) = 48.990 V RMS
Vout = Vref × 10^(level/20)
Irms = Vout / 8 Ω · P = Vout² / 8 Ω</div><p class="note">Pure 8 Ω resistor teaching load; 0 dB is the manufacturer's 300 W/8 Ω rating. This is not a W13 impedance model, actual volume calibration, instantaneous mains draw, or thermal simulation.</p><div class="formula">Controlled output + → 8 Ω load → output −
Signal pair → input reference / return
AC supply → energy storage → output stage</div><p>For the resistor, voltage and current are in phase and instantaneous power is nonnegative. A real loudspeaker stores and returns energy and has a complex, frequency-dependent impedance. The amplifier can supply current in either direction.</p>${cites('amp')}`,
speakers:`<h3>Force → motion → pressure</h3><p>The separate cutaway shows a generic moving-coil transducer. Current interacts with magnetic flux to exert force; the coil and cone move, disturbing nearby air. The actual W13 cabinet stays intact.</p><button class="action" id="airButton" aria-pressed="false">Show local air motion</button><canvas class="chart" id="physicsChart" aria-label="Pressure wave with local oscillating air particles"></canvas><div class="control"><label for="spl">Illustrative pressure level <output id="splOut"></output></label><input id="spl" type="range" min="60" max="100" value="80" step="1"></div><div id="metrics"></div><div class="formula">pRMS = 20 μPa × 10^(SPL/20)
uRMS = pRMS / (ρc)
ξpeak = √2 uRMS / (2πf)
λ = c/f · travel time = distance/c</div><p class="note">Progressive plane wave in air: ρ = 1.204 kg/m³, c = 343 m/s. Plot spans two wavelengths, a normalized spatial scale. One cycle displayed in 2 s: slowdown = 2f. Each particle oscillates locally; it does not ride the pressure crest.</p><p class="note">3D insert: schematic motion at 0.6 Hz, cone ±8 mm and air ±12 mm for visibility, unrelated to the quantitative plane-wave excursion. Cone/coil motion is shown; detailed suspension deformation is omitted. No actual cone excursion is predicted. Small-signal force principle F = Bℓi; W13 Bℓ, moving mass and compliance are unspecified.</p><h3>The integrated subwoofers and the room</h3><p>The W13’s side woofers reproduce the longest wavelengths using their own DSP and amplifiers. Reflections combine with direct sound, creating pressure maxima and minima that depend on frequency and position. The enclosure’s integrated subwoofers are the bass sources in this installation.</p><div class="control"><label for="roomLength">Ideal room length <output id="roomOut"></output></label><input id="roomLength" type="range" min="4" max="9" value="6" step=".1"></div><div id="roomMetrics"></div><div class="formula">Rectangular-room modes:
f(n,m,p) = (c/2) √[(n/L)²+(m/W)²+(p/H)²]
L variable · W = 4.5 m · H = 2.8 m
c = 343 m/s · rigid ideal boundaries</div><p class="note">This acoustic model is separate from the photographed room. Its dimensions are assumptions, not a measured survey. Axial-mode frequencies are not response amplitudes. Losses, furnishings, openings and source/listener placement are omitted.</p>${cites('wave','sound')}`

};
